### ISSUE TITLE
Viewer's map view does not match the design

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#106]
1. At the map view, the "player-viewer" switch is display as default for viewers, when we agreed that the   "player-viewer" switch will only appear after viewers choose a player's marker.
2. At the left and bottom of the screen displays the text "viewer", instead of the viewer's username.
3. For viewers default view (and as long as they have'nt took control over player's character), all the players's markers should be display without white circle inside (white circle = my player).

**Comment by eitanfr** [comment]
1 & 2 done
3 - wait for all markers

**Comment by stavbsh** [comment]
Characters's markers attached to issue #70

**Comment by OmKoren** [comment]
player-viewer switch should appear only after selection of a character from map.
hover - no need
selection - change to green
