### ISSUE TITLE
Fix the players statuses at the waiting screen

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#138]
Display one from the four statuses below:
1. Waiting: display this status for players who haven't clicked on the   "I'm ready" button.
2. Ready: display this status for players who clicked on the "I'm   ready" button.
3. Active: display this status for players who already entered the game and   their characters is still alive.
4. Inactive: display this status for players who already entered the game   and their characters died.

**Comment by OmKoren** [comment]
waiting or ready only
