### ISSUE TITLE
the game's code is available to the users only from it's waiting screen, after entering the game they have no access to it anymore

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#32]
**what to do:**
add a settings menu button that allows the users to see the game's code (same solution for issue 31).
see screenshot below:
<img width="1920" alt="add settings button" src="https://user-images.githubusercontent.com/29520993/32067703-cfc0f2c4-ba8c-11e7-811e-df50c03a1762.png">

**Comment by eitanfr** [comment]
Related to #31
