### ISSUE TITLE
users who entered the game as players can't acces the map view

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#33]
**priority:**
critical

**what to do:**
add to the players the ability to enter the map view using the TAB key.

**Comment by eitanfr** [comment]
M will allow you to move to overview

**Comment by stavbsh** [comment]
Users who entered the game as players need the ability to enter/exit the map view using the M key. 

If the users made a double click over their own character’s marker/pressed the M key, they’ll get back into their character’s semi-fpv.

If the users have clicked over another character’s marker, the switch button will appear above their username and character's portrait (left bottom corner of the screen), what gives them the ability to take control over the new character and get into the character's semi-fpv.
After a player took control over a new character the character’s portrait  will change according to it.
