### ISSUE TITLE
The color from the inside of the building isn't black

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#53]
Change the color of the walls, floor and ceiling into black.
as the screenshot below:
<img width="1920" alt="semi fpv - inside a building" src="https://user-images.githubusercontent.com/29520993/32143620-cd2d8ec6-bcb4-11e7-9d6f-9018b6a84e6c.png">

**Comment by eitanfr** [comment]
the original solution for the window was creating black div with a "hole" to simulate window, and the player could only move forward and backward. the current solution simulates an actual room allowing the user to move freely inside the building, sure  we want the black color? maybe another color?

**Comment by eitanfr** [comment]
dark gray
