### ISSUE TITLE
The original design doesn't support  multi-rooms gaming

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#57]
Update the login screen with the new design that support multi-rooms gaming.

<img width="1920" alt="login screen - new game" src="https://user-images.githubusercontent.com/29520993/32144746-61f371e0-bcc6-11e7-8728-bfa10ba590f8.png">

<img width="1920" alt="login screen - join game" src="https://user-images.githubusercontent.com/29520993/32144754-6ffd1da4-bcc6-11e7-85ec-06c623972260.png">

**Comment by eitanfr** [comment]
nice
