### ISSUE TITLE
Update the "how to play" screen with the new operation keys

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#58]
Make sure your'e using the right operation keys (see issue 38), and that the help button is in active mode.
see the screenshot below:
<img width="1920" alt="how to play" src="https://user-images.githubusercontent.com/29520993/32145263-12851692-bcce-11e7-9d9f-085342883cd4.png">

**Comment by eitanfr** [comment]
Related to #38

**Comment by stavbsh** [comment]
Updated screen design:
<img width="1920" alt="how to play - new" src="https://user-images.githubusercontent.com/29520993/32225147-cc8ed35a-be4c-11e7-8697-806595d99c48.png">
