### ISSUE TITLE
The shooting mode screen doesn't match the original design.

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#59]
Fix the gun sight design, see the screenshot below:
<img width="1920" alt="semi fpv - shooting mode" src="https://user-images.githubusercontent.com/29520993/32144985-23b8fcd4-bcca-11e7-8672-80845f07943e.png">

**Comment by eitanfr** [comment]
sure you prefer this design? 
I think the current icon looks better,
