### ISSUE TITLE
The message "enter E to enter the building" doesn't appear as a toast message

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#61]
Fix it so it will appear as a toast message:
![toast 3](https://user-images.githubusercontent.com/29520993/32145400-7161d662-bcd0-11e7-8aa3-809337e42aad.png)

**See instructions below:**
![toast 2](https://user-images.githubusercontent.com/29520993/32145399-7142c9b6-bcd0-11e7-80c7-9efac2333d5e.png)
Text: 48pt, Agency FB, Regular, #FFFFFF, align center
Backgtound color: #000000, 54%

**Comment by tomermoshe** [comment]
fixed with #95
