### ISSUE TITLE
There isn't indicator to shooting's action over the player's characters marker (map view)

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#62]
Insert a shooting indicator 4dp above the shooting character's marker:
![captian america2](https://user-images.githubusercontent.com/29520993/32145533-15dcf56c-bcd3-11e7-8270-fe036f1d90ac.png)

**Comment by davidyaha** [comment]
Fixed in #89

**Comment by stavbsh** [comment]
On the map view,  a pistol should be display above a character's marker for as long as the player stays in shooting mode (it shouldn't represent a shot, but being in shooting mode).

**Comment by stavbsh** [comment]
After that players have entered shooting mode and then shifted to map view, the player's marker shouldn't have a shooting mode modifier (shifting to map view is equal to exiting shooting mode).

Therefore, the shooting mode modifier shouldn't be display for the other players as well.

Here's a screenshot of the problem:
![shooting mode infdicator for my character](https://user-images.githubusercontent.com/29520993/32990614-17bafbdc-cd35-11e7-9e10-73b21f72e9fa.png)

**Comment by davidyaha** [comment]
We will add shooting indicator on the player's map view

**Comment by eitanfr** [comment]
fix #151
