### ISSUE TITLE
Instructions screen missing

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#63]
Add an "instructions" message that appears in the first screen of the game.

See screenshot below:
<img width="1920" alt="instruction - two player" src="https://user-images.githubusercontent.com/29520993/32145733-09cd025a-bcd6-11e7-84dc-4ad47f681bb8.png">

**Comment by eitanfr** [comment]
Will be put on game room

**Comment by eitanfr** [comment]
#82
