### ISSUE TITLE
The characters's marker in the map view doesn't match the original design

### ISSUE THREAD

**Issue by stavbsh** [Webiks/CesiumFPS#70]
Update character markers as per design document
[Style guide 29.10.17.docx](https://github.com/Webiks/CesiumFPS/files/1425351/Style.guide.29.10.17.docx)

**Comment by stavbsh** [comment]
The zip file attached contains all the icons in svg's format
[svg icons.zip](https://github.com/Webiks/CesiumFPS/files/1430887/svg.icons.zip)

**Comment by stavbsh** [comment]
Ironman's marker is displayed as "my player" (white circle inside the marker) regardless the player's actual character.

here's a screenshot of the problem:
![ironman marker as my player](https://user-images.githubusercontent.com/29520993/32734339-6eae5b04-c89a-11e7-8fc0-51c580610492.png)

**Comment by stavbsh** [comment]
Attached a zip file with all characters's markers
[markers.zip](https://github.com/Webiks/CesiumFPS/files/1475300/markers.zip)

**Comment by stavbsh** [comment]
1. Fix the label's design as section 2 above.
2. Fix the design for hover and chosen states:
<img width="605" alt="markers hover and chosen" src="https://user-images.githubusercontent.com/29520993/32989839-d52c742a-cd26-11e7-9a52-ab8f47f198ae.png">

**Comment by davidyaha** [comment]
Will be handled in #106
